// Code generated by protoc-gen-go. DO NOT EDIT.
// source: option/http.proto

package option

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Http struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Http) Reset()         { *m = Http{} }
func (m *Http) String() string { return proto.CompactTextString(m) }
func (*Http) ProtoMessage()    {}
func (*Http) Descriptor() ([]byte, []int) {
	return fileDescriptor_5aacaeeef1dd06c7, []int{0}
}

func (m *Http) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http.Unmarshal(m, b)
}
func (m *Http) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http.Marshal(b, m, deterministic)
}
func (m *Http) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http.Merge(m, src)
}
func (m *Http) XXX_Size() int {
	return xxx_messageInfo_Http.Size(m)
}
func (m *Http) XXX_DiscardUnknown() {
	xxx_messageInfo_Http.DiscardUnknown(m)
}

var xxx_messageInfo_Http proto.InternalMessageInfo

func (m *Http) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Http) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

var E_Http = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Http)(nil),
	Field:         50000,
	Name:          "pb.option.http",
	Tag:           "bytes,50000,opt,name=http",
	Filename:      "option/http.proto",
}

func init() {
	proto.RegisterType((*Http)(nil), "pb.option.Http")
	proto.RegisterExtension(E_Http)
}

func init() { proto.RegisterFile("option/http.proto", fileDescriptor_5aacaeeef1dd06c7) }

var fileDescriptor_5aacaeeef1dd06c7 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x2f, 0x28, 0xc9,
	0xcc, 0xcf, 0xd3, 0xcf, 0x28, 0x29, 0x29, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2c,
	0x48, 0xd2, 0x83, 0x88, 0x4a, 0x29, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83, 0x25, 0x92,
	0x4a, 0xd3, 0xf4, 0x53, 0x52, 0x8b, 0x93, 0x8b, 0x32, 0x0b, 0x4a, 0xf2, 0x8b, 0x20, 0x8a, 0x95,
	0x8c, 0xb8, 0x58, 0x3c, 0x4a, 0x4a, 0x0a, 0x84, 0xc4, 0xb8, 0xd8, 0x72, 0x53, 0x4b, 0x32, 0xf2,
	0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x21, 0x21, 0x2e, 0x96, 0x82, 0xc4,
	0x92, 0x0c, 0x09, 0x26, 0xb0, 0x28, 0x98, 0x6d, 0xe5, 0xca, 0xc5, 0x02, 0xb2, 0x4e, 0x48, 0x4e,
	0x0f, 0x62, 0xbc, 0x1e, 0xcc, 0x78, 0x3d, 0x5f, 0xb0, 0x26, 0x7f, 0xb0, 0xe5, 0xc5, 0x12, 0x17,
	0xda, 0x98, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0xf8, 0xf5, 0xe0, 0x2e, 0xd2, 0x03, 0x59, 0x16, 0x04,
	0xd6, 0xee, 0xc4, 0x11, 0xc5, 0x06, 0x11, 0x4c, 0x62, 0x03, 0x1b, 0x60, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xc6, 0xec, 0x23, 0x8e, 0xcd, 0x00, 0x00, 0x00,
}
